### ISSUE TITLE
Minor issue in README

### ISSUE THREAD

**Issue by byrongibby** [troy-west/cronut#9]
The [README](https://github.com/troy-west/cronut#integrant) incorrectly states that `troy-west.cronut/data-readers` includes a reader function for tag `ig/ref`. Consider changing from `edn/read-string` to `ig/read-string` as the latter merges in `ig/ref`?

Just a small thing that caused me a little confusion.

**Comment by d-t-w** [comment]
Thanks for raising this @byrongibby, I've updated the README.
